### ISSUE TITLE
Update won't let me delete Piece files

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/elvis-database#107]
I'm trying to delete movements that I accidentally uploaded as "Piece" files when I was first trying out the database, and it shows an error each time, at least on the two pieces I tried.

**Comment by lexpar** [comment]
This is because I'm changing stuff on the back end of the site -  sorry - I should put up a down for maintenance thing.

**Comment by emilyhopkins** [comment]
ah, ok, good, because I was just about to write saying that it was making new and different problems mere minutes apart! That would explain it :)

**Comment by lexpar** [comment]
I've removed the lock from the site - please let me what you were trying to do now works.

**Comment by emilyhopkins** [comment]
There's no error anymore, but it doesn't actually delete the files:

<img width="1920" alt="screen shot 2015-08-17 at 4 00 37 pm" src="https://cloud.githubusercontent.com/assets/13374693/9314803/3f30dcc0-44f9-11e5-87a4-096306f258ab.png">

As I understand it, only the movements should show up, with their files accessible once I click through to them. But the automatically-named piece files are still showing up.

**Comment by lexpar** [comment]
I'm a little confused now - what exactly are you trying to do?

**Comment by emilyhopkins** [comment]
Based on other pieces with movement files but no piece files (e.g. http://database.elvisproject.ca/piece/2864/) I don't think the Available Attachments should be there -- they're not piece files, they're movement files I uploaded in the wrong place.

When trying to update I delete the files with those names but they don't go away.

**Comment by lexpar** [comment]
Right - apologies for not understanding at first. I think I just fixed your problem, please have another go and let me know.

**Comment by emilyhopkins** [comment]
Still not working... (for either Refresh Page or going to the updated piece...)

**Comment by lexpar** [comment]
I was able to delete them through the update page... Your browser is probably loading a cached version of the script.

http://database.elvisproject.ca/piece/2809/

**Comment by emilyhopkins** [comment]
Hooray! Cleared cache and now it works. Thanks!
